export const TIME_IN_SECONDS = {
	HALF_MINUTE: 30,
	MINUTE: 60,
	HOUR: 3600,
	DAY: 86400,
	WEEK: 86400 * 7,
} as const;

export const NOTES_CACHE_POLICY = {
	PRIVATE_MAX_AGE_SECONDS: TIME_IN_SECONDS.WEEK,
	PRIVATE_STALE_WHILE_REVALIDATE_SECONDS: TIME_IN_SECONDS.DAY,
	PUBLIC_MAX_AGE_SECONDS: TIME_IN_SECONDS.MINUTE * 2,
	PUBLIC_S_MAXAGE_SECONDS: TIME_IN_SECONDS.HOUR,
	PUBLIC_STALE_WHILE_REVALIDATE_SECONDS: TIME_IN_SECONDS.DAY,
} as const;
